- block:
  - name: Stop and remove the web app container
    community.docker.docker_container:
      name: web_app_container
      state: absent

  when: web_app_full_wipe is defined and web_app_full_wipe == true
  tags: wipe
