name: Python CI

on:
  pull_request:
    paths:
      - 'lab1/app_python/**'
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Cache pip dependencies
      uses: actions/cache@v2
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r lab1/app_python/requirements.txt

    - name: Lint with flake8
      run: |
        pip install flake8
        flake8 . --ignore=E501,E402

    - name: Test with pytest
      run: |
        pytest

    - name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: ./lab1/app_python/
        file: lab1/app_python/Dockerfile
        push: true
        tags: aisenbeast/inno-devops:latest

    - name: Run Snyk to check for vulnerabilities
      uses: snyk/actions/python@master
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      with:
        args: --file=lab1/app_python/requirements.txt
          --package-manager=pip
          --skip-unresolved